services:
  app:
    build: .
    command: python -u ./web-app/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=;angs
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./db/languages.js:/docker-entrypoint-languages.d/languages.js:ro 
    ports:
      - 27017:27017
  ml-client:
    build: ./machine-learning-client
    volumes:
      - .:/machine-learning-client